#' Cairo wrapper function
#'
#' Cairo wrapper function retuning NULL if not \code{type} is specified
#'
#' \code{openGraphCairo()} \code{Cairo()} wrapper function. Differences to \code{Cairo:}
#' a) prematurely ends the function call to \code{Cairo()}  returning NULL, if no output \code{type} is provided.
#' b) \code{file}should not include file extension "."\code{type}. File name is generated by pasting \code{file}  with "." \code{type}extension.
#' c)  magnifies graphics device output by factor \code{mag}. 

#' @param width see \code{Cairo()}
#' @param height see \code{Cairo()}
#' @param file name of file to be created or connection to write to without file extension ".\code{type}". Default file name "visstat". 
#' @param type see \code{Cairo()}
#' @param pointsize see \code{Cairo()}
#' @param bg see \code{Cairo()}
#' @param canvas see \code{Cairo()}
#' @param units see \code{Cairo()}
#' @param dpi DPI used for the conversion of units to pixels. Default value 150. 
#' @param mag multiplies both \code{width} and \code{height} by magnification factor \code{mag}.
#' @name openGraphCairo
#' @return NULL, if no type is specified. Otherwise see \code{Cairo()}
#' @examples
#' # return NULL
#' openGraphCairo()
#' 
#' #  adapted from example in \code{Cairo()}
#' openGraphCairo(type="png",mag=2.54) #mag is conversion factor cm to inch
#' plot(rnorm(4000),rnorm(4000),col="#ff000018",pch=19,cex=2) # semi-transparent red
#' dev.off() # creates a file "visstat_plot.png" with the above plot
#' # remove the example files if not in an interactive session
#' if (!interactive()) unlink(c("visstat_plot.png","plot.pdf"))


#' @import Cairo
#' 
#' @export openGraphCairo

  openGraphCairo =  function(width = 640,
           height = 480 , file = NULL, type = NULL, pointsize = 12,
           bg = "transparent", canvas = "white", units = "px",
           dpi=150, mag=1) 
   
    
     
  {
  if (is.null(type))
  {return()}
  else{
  if (is.null(file)) {
    file = "visstat_plot"}

Cairofilename = paste(file, ".", type, sep = "")

if (type == "png") {
CairoPNG(filename = Cairofilename)  
  
}
else{
Cairo(Cairofilename,
        type = type,
        width = width * mag,
        height = height * mag,
        units = units,
        dpi = dpi,
        pointsize = pointsize)
}  

  }   
}


