#' Visualisation of the normality distribution of the standardised residuals
#'
#' \code{vis_anova_assumptions} checks for normality of the standardised
#' residuals. Both the Shapiro-Wilk test \code{shapiro.test()} and
#' the Anderson-Darling test \code{ad.test()} check the null that the
#' standardised residuals are normally distributed. It generates a scatter plot
#' of the standardised residuals versus the fitted values. Furthermore a normal QQ plot of the
#' standardised residuals vs the theoretical quantiles is generated. For ANOVA, the null of
#' homogeneity of variances of each factor level is tested with the \code{bartlett.test()}.
#'
#' @param samples vector containing dependent variable, datatype numeric
#' @param fact vector containing independent variable, datatype factor
#' @param conf.level confidence level, 0.95=default
#' @param samplename name of sample used in graphical output, datatype character, ''=default
#' @param factorname name of factor used in graphical output, datatype character, ''=default
#' @param cex number indicating the amount by which plotting text and symbols
#'   should be scaled relative to the default. 1=default, 1.5 is 50\% larger,
#'   0.5 is 50\% smaller, etc.
#' @param regression logical, if TRUE skips Bartlett test (for regression diagnostics), default FALSE
#'
#' @return \code{list} containing the test statistics, the p values
#'   generated by the Shapiro-Wilk test \code{shapiro.test()}, the
#'   Anderson-Darling test \code{ad.test()} and optionally the \code{bartlett.test()}.
#'
#' @examples
#' ToothGrowth$dose <- as.factor(ToothGrowth$dose)
#' vis_anova_assumptions(ToothGrowth$len, ToothGrowth$dose)
#'
#' vis_anova_assumptions(ToothGrowth$len, ToothGrowth$supp)
#' vis_anova_assumptions(iris$Petal.Width, iris$Species)
#'
#' @export vis_anova_assumptions

vis_anova_assumptions <- function(samples, fact, conf.level = 0.95, 
                                  samplename = "", factorname = "", cex = 1, regression = FALSE) {
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))
  
  anova_model <- aov(samples ~ fact)
  std_residuals <- rstandard(anova_model)
  n_residuals <- length(std_residuals)
  
  # Statistical tests
  if (n_residuals >= 3 && n_residuals <= 5000) {
    shapiro_test <- shapiro.test(std_residuals)
  } else if (n_residuals < 3) {
    shapiro_test <- list(statistic = NA, p.value = NA, method = paste("Shapiro-Wilk test requires at least 3 observations (n =", n_residuals, ")"))
  } else {
    shapiro_test <- list(statistic = NA, p.value = NA, method = paste("Shapiro-Wilk test requires sample size ≤ 5000 (n =", n_residuals, ")"))
  }
  
  if (n_residuals >= 7) {
    ad_test <- nortest::ad.test(std_residuals)
  } else {
    ad_test <- "Anderson-Darling test requires sample size of at least 7."
  }
  
  if (!regression) {
    bartlett_test <- bartlett.test(samples ~ fact)
  }
  
  # Create plots
  par(mfrow = c(1, 3), cex = 0.7*cex, oma = c(0, 0, 2, 0))
  
  x_min <- min(min(std_residuals), -3.2)
  x_max <- max(max(std_residuals), 3.2)
  temp_hist <- hist(std_residuals, plot = FALSE)
  y_max <- max(max(temp_hist$density), 0.45)
  
  hist(std_residuals, freq = FALSE, main = "Hist. of Std. Res.", 
       xlab = "Std. Residuals", col = "lightblue", border = "black",
       xlim = c(x_min, x_max), ylim = c(0, y_max))
  x_seq <- seq(x_min, x_max, length.out = 200)
  lines(x_seq, dnorm(x_seq), col = "red", lwd = 2)
  
  plot(fitted(anova_model), std_residuals, main = "Std. Res. vs. Fitted", ylab="Std. Residuals", xlab="Fitted values")
  abline(h = 0, col = "black", lwd = 2)
  
  qqnorm(std_residuals)
  qqline(std_residuals, col = "red", lwd = 2)
  
  # Title
  p_shapiro <- if (!is.na(shapiro_test$p.value)) signif(shapiro_test$p.value, 3) else "N/A"
  p_AD <- if (is.list(ad_test)) signif(ad_test$p.value, 3) else "N/A"
  
  if (regression) {
    mtext(text = paste("Shapiro p =", p_shapiro, "| Anderson-Darling p =", p_AD), 
          side = 3, outer = TRUE, cex = 0.8)
  } else {
    mtext(text = paste("Shapiro p =", p_shapiro, "| Anderson-Darling p =", p_AD, "| Bartlett p =", signif(bartlett_test$p.value, 3)), 
          side = 3, outer = TRUE, cex = 0.8)
  }
  
  # Return results
  result <- list(summary_anova = summary(anova_model), shapiro_test = shapiro_test, ad_test = ad_test)
  if (!regression) result$bartlett_test <- bartlett_test
  result
}