#' Visualisation of the normality distribution of the standardised residuals of the ANOVA
#'
#' \code{vis_anova_assumptions} checks for normality of the standardised
#' residuals of the ANOVA. Both the Shapiro-Wilk test \code{shapiro.test()} and
#' the Anderson-Darling test \code{ad.test()} check the null that the
#' standardised residuals are normally distributed. It generates a scatter plot
#' of the standardised residuals versus the fitted mean values of the linear
#' models for each level of \code{fact}. Furthermore a normal QQ plot of the
#' standardised residuals vs the theoretical quantiles is generated. The null of
#' homogeneity of variances of each factor level is tested with the \code{bartlett.test()}.
#'
#' @param samples vector containing dependent variable, datatype numeric
#' @param fact vector containing independent variable, datatype factor
#' @param conf.level confidence level, 0.95=default
#' @param samplename name of sample used in graphical output, datatype character, ''=default
#' @param factorname name of factor used in graphical output, datatype character, ''=default
#' @param cex number indicating the amount by which plotting text and symbols
#'   should be scaled relative to the default. 1=default, 1.5 is 50\% larger,
#'   0.5 is 50\% smaller, etc.
#'
#' @return \code{list} containing the test statistics of the anova, the p values
#'   generated by the Shapiro-Wilk test \code{shapiro.test()}, the
#'   Anderson-Darling test \code{ad.test()} and the \code{bartlett.test()}.
#'
#' @examples
#' ToothGrowth$dose <- as.factor(ToothGrowth$dose)
#' vis_anova_assumptions(ToothGrowth$len, ToothGrowth$dose)
#'
#' vis_anova_assumptions(ToothGrowth$len, ToothGrowth$supp)
#' vis_anova_assumptions(iris$Petal.Width, iris$Species)
#'
#' @export vis_anova_assumptions

vis_anova_assumptions_old <- function(samples, fact, conf.level = 0.95, 
                                  samplename = "", factorname = "", cex = 1) {
  # Store original par settings
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))
  
  
  # Fit ANOVA model
  anova_model <- aov(samples ~ fact)
  std_residuals <- rstandard(anova_model)
  
  # Statistical tests
  shapiro_test <- shapiro.test(std_residuals)
  bartlett_test <- bartlett.test(samples ~ fact)
  
  # Anderson-Darling test (requires n >= 7)
  if (length(std_residuals) >= 7) {
   ad_test <- nortest::ad.test(std_residuals)
  } else {
    ad_test <- "Anderson-Darling test requires sample size of at least 7."
  }
  
  # Create plots
  
  par(mfrow = c(1, 3), cex = 0.7*cex, oma = c(0, 0, 2, 0)) # outer margins oma
  # needed for title
  
  
  # Plot 1: Histogram with normal overlay
  x_min <- min(min(std_residuals), -3.2)
  x_max <- max(max(std_residuals), 3.2)
  
  # Get histogram data first to check its max
  temp_hist <- hist(std_residuals, plot = FALSE)
  hist_max <- max(temp_hist$density)
  
  # Ensure y-axis shows at least the N(0,1) peak (~0.399)
  y_max <- max(hist_max, 0.45)  # 0.45 > 0.399 with buffer
  
  hist(std_residuals, freq = FALSE, main = "Hist. of Std. Res.", 
       xlab = "Std. Residuals", col = "lightblue", border = "black",
       xlim = c(x_min, x_max), ylim = c(0, y_max))
  
  x_seq <- seq(x_min, x_max, length.out = 200)
  normal_curve <- dnorm(x_seq, mean = 0, sd = 1)
  lines(x_seq, normal_curve, col = "red", lwd = 2)
  
  # Plot 2: Residuals vs Fitted
  plot(fitted(anova_model), std_residuals, main = "Std. Res. vs. Fitted",ylab="Std. Residuals", xlab="Fitted values")
  abline(h = 0, col = "black", lwd = 2)
  
  # Plot 3: Q-Q Plot
  qqnorm(std_residuals)
  qqline(std_residuals, col = "red", lwd = 2)
  
  # Add p-values as overall title
  if (is.list(ad_test)) {
    p_AD <- signif(ad_test$p.value, 3)
  } else {
    p_AD <- "N/A"
  }
  
  mtext(text = paste("Shapiro p =", signif(shapiro_test$p.value, 3),
                     "| Anderson-Darling p =", p_AD,
                     "| Bartlett p =", signif(bartlett_test$p.value, 3)
                     ), 
        side = 3, outer = TRUE, cex = 0.8)
  
  # Return results
  list(
    summary_anova = summary(anova_model),
    shapiro_test = shapiro_test,
    ad_test = ad_test,
    bartlett_test = bartlett_test
  )
}