url: https://shhschilling.github.io/visStatistics/

template:
  bootstrap: 5
  params:
    number_sections: yes

encoding: UTF-8

home:
  title: visStatistics
  sidebar: no

navbar:
  structure:
    left:
      - home
      - reference
      - articles
  components:
    vignette:
      text: Vignette
      href: articles/visStatistics.html

articles:
  - title: Vignette
    toc: true
    toc_depth: 4
    style: sidebar
    contents:
      - visStatistics
